### ISSUE TITLE
Google Maps is not showing the map on the application

### ISSUE THREAD

**Issue by m-cheraim** [HabitatMap/AirCastingAndroidClient#26]
Hello,
I set an API key (that is tested and working on another Android application).
But trying to access to Google Maps from this application, the map doesn't show up.
And that's the error I get many times on the Run console:

`I/System.out: Thread-42266(ApacheHTTPLog):isSBSettingEnabled false`
`    Thread-42266(ApacheHTTPLog):isShipBuild true`
`    Thread-42266(ApacheHTTPLog):getDebugLevel 0x4f4c`
`    Thread-42266(ApacheHTTPLog):Smart Bonding Setting is false`
`    Thread-42266(ApacheHTTPLog):SmartBonding Setting is false, SHIP_BUILD is true, log to file is false, DBG is false, DEBUG_LEVEL (1-LOW, 2-MID, 3-HIGH) is 1`
`W/System.err: IOException processing: 26`
`    java.io.IOException: Server returned: 3`
`        at android_maps_conflict_avoidance.com.google.googlenav.map.BaseTileRequest.readResponseData(BaseTileRequest.java:115)`
`        at android_maps_conflict_avoidance.com.google.googlenav.map.MapService$MapTileRequest.readResponseData(MapService.java:1473)`
`        at android_maps_conflict_avoidance.com.google.googlenav.datarequest.DataRequestDispatcher.processDataRequest(DataRequestDispatcher.java:1117)`
`        at android_maps_conflict_avoidance.com.google.googlenav.datarequest.DataRequestDispatcher.serviceRequests(DataRequestDispatcher.java:994)`
`        at android_maps_conflict_avoidance.com.google.googlenav.datarequest.DataRequestDispatcher$DispatcherServer.run(DataRequestDispatcher.java:1702)`
`        at java.lang.Thread.run(Thread.java:818)`
`I/System.out: DataRequestDispatcher calls detatch()`

Can you know why I get this issue ?

Thank you.

**Comment by mheimbinder** [comment]
Hello.  I'm not sure what the source of the error is.  I've found Google to
be responsive to questions regarding their maps API.  Please try emailing
their technical support team.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by m-cheraim** [comment]
Ok, thank you.
One other question. is that application maps (using maps-7_r1 package) tested with a new generated API keys ? I wonder how any generated API key works on a map test application that uses 'play-services-maps' package but doesn't work on this application.
